/**
 * DO NOT EDIT THIS FILE
 */
import { useEffect, useState } from "react";
import { getServerState } from "./utils/async";

export default function ServerState() {
  const [serverState, setServerState] = useState("");

  useEffect(() => {
    setInterval(async () => {
      setServerState(await getServerState());
    }, 100);
  }, []);

  return (
    <div>
      <h4>Server's State</h4>
      <div className="server">{serverState}</div>
    </div>
  );
}
